fix: sanitize html in highlighted code
crabnebula-dev/devtools pull request #164
Opened 2023-12-13 10:08 UTC by CrabNejonas

This adds `sanitize-html` to sanitize the HTML we include in the page through `innerHTML` which can *technically* be used to execute untested code (the chance is very low, but sanitizing here is low overhead afaik and simple to include)

2023-12-13 12:25 UTC, lucasfernog-crabnebula approved these changes

2023-12-13 12:25 UTC, lucasfernog-crabnebula commented on web-client/src/components/span/span-detail.tsx
> -        ? null
we're not returning `null` anymore, i hope this doesn't break anything

2023-12-13 12:27 UTC, johann-crabnebula commented
I would like to split the shiki highlighting and and the source loading. So that we can simply give a string value to the shiki highlight component. That would reduce redundancy.

2023-12-13 12:29 UTC, johann-crabnebula requested changes
I will open a PR with a little proposal.

2023-12-13 13:01 UTC, johann-crabnebula commented
Here is the PR: https://github.com/crabnebula-dev/devtools/pull/166
@CrabNejonas 

Let me know what you think.

2023-12-14 13:53 UTC, atila-crabnebula requested changes
It seems there's [no consensus](https://github.com/crabnebula-dev/devtools/pull/166#discussion_r1426125064) about which sanitization library is better to use.

In addition, we have talked about moving code parsing and highlighting out of the main thread **before** doing this and replacing Shiki with Shikiji before.

So let's hold out on merging temporary code to `main`.

2023-12-18 13:10 UTC, closed without merging