feat: add Tauri v2 support
crabnebula-dev/devtools pull request #173
Opened 2024-01-02 12:32 UTC by lucasfernog-crabnebula

This pull request changes the devtools Tauri plugin to use the Tauri v2 alpha. It has been tested on macOS, Linux, iOS and Android.

It is still a draft because we should decide how to maintain both versions of the plugin. Probably the v2 should live in a separate repo/branch.
Also it needs a Tauri PR / release before merging.

Needs #171

2024-01-09 16:47 UTC, lucasfernog-crabnebula commented
@CrabNejonas this one is ready for review (I'm marking it as draft because we want to move the v2 plugin out of this repo - or keep it on a separate branch - and merge the rest).

2024-01-15 15:05 UTC, CrabNejonas approved these changes
As we said the frontend work needs to be merged into v1.x too (right now the 1.x frontend can't connect to the 2.x frontend) but otherwise this looks good to me 👍

2024-01-15 17:50 UTC, lucasfernog-crabnebula commented on web-client/src/lib/span/get-span-children.ts
this is only checked once when the span is incoming so idk if it's worth the overhead of storing it instead.. i'll leave it to you guys later

2024-01-15 18:02 UTC, johann-crabnebula commented
This is UX issue:

I noticed that the Cert breaks the console display since it overflows:

![chrome_SUA6ST2eIT](https://github.com/crabnebula-dev/devtools/assets/119593300/42fc46ec-0484-4a80-b13b-0acfcc6611f1)

2024-01-15 18:03 UTC, johann-crabnebula requested changes
Noticed that the sources are not working for me on Android:

![chrome_SlSVMTcB5U](https://github.com/crabnebula-dev/devtools/assets/119593300/b8cd0d41-9a86-4c78-8b3b-5b3a2d6364bc)

```sh
01-15 18:23:39.935  6985  7048 I RustStdoutStderr: 2024-01-15T18:23:39.935495Z ERROR devtools::server: List Entries failed with error Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
```

2024-01-15 20:58 UTC, johann-crabnebula approved these changes
I will approve the frontend, so we can move forward.

2024-01-17 02:43 UTC, merged